language: cpp

os:
  - osx
  - linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

compiler:
  - clang

script: ./build.sh

notifications:
  email:
    - kishwar.shafin@gmail.com

env:
  global:
  - LANG="en_US.UTF-8"